name: Restreamer_Server_New
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: تشغيل برنامج ريستريمر ونغروك
        run: |
          # 1. تشغيل برنامج ريستريمر في الخلفية
          docker run -d --restart always \
            --name restreamer \
            -p 8080:8080 -p 8181:8181 \
            -p 1935:1935 -p 1936:1936 \
            -p 6000:6000/udp \
            datarhei/restreamer:latest

          # 2. تحميل وتثبيت أداة نغروك
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          
          # 3. تفعيل المفتاح الجديد الخاص بك
          ngrok config add-authtoken 38NrjU0MIMesF1mkhrJoGbJ98yM_3UnTr2x3SSEQmYLdpuunb

          # 4. فتح رابط التحكم (سيظهر الرابط في الأسفل بعد ثوانٍ)
          echo "جاري استخراج رابط التحكم..."
          ngrok http 8080 --log=stdout > /dev/null &
          sleep 20
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
          
          # 5. ترك السيرفر يعمل لمدة 6 ساعات
          echo "السيرفر يعمل الآن بنجاح.."
          sleep 21600
